# Generated by Django 3.0.6 on 2020-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_added_default_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='review_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
