# Generated by Django 3.0.6 on 2020-10-16 07:46

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('description', models.TextField(max_length=2000)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('work_from', models.TimeField()),
                ('work_to', models.TimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantContacts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Restaurant Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('restaurant.restaurant',),
        ),
    ]
