# Generated by Django 3.0.6 on 2020-10-20 07:13

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('calories', models.IntegerField()),
                ('weight', models.FloatField()),
                ('category', models.CharField(choices=[('pizza', 'pizza'), ('burger', 'burger'), ('sushi', 'sushi'), ('first meal', 'first meal'), ('second meal', 'second meal'), ('dessert', 'dessert')], max_length=100)),
                ('photo', models.ImageField(upload_to='dish')),
            ],
            options={
                'verbose_name_plural': 'Dish',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='drinks')),
                ('bottle_volume', models.CharField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2')], max_length=150)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateField(default=menu.models.get_expire_date)),
                ('price', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DayDish', to='menu.Dish')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drink', to='menu.Drink')),
            ],
            options={
                'verbose_name_plural': 'Menu of day',
            },
        ),
    ]
