# Generated by Django 3.0.6 on 2020-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='dish/default.png', upload_to='dish'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(default='drinks/default.png', upload_to='drinks'),
        ),
    ]
