# Generated by Django 3.0.6 on 2020-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201026_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('drink', 'drink'), ('dish', 'dish')], max_length=200)),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
