# Generated by Django 3.0.6 on 2020-11-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
